//
// Created by jora on 4/6/21.
//

#ifndef CRAWLER_LINKENTRYREPOSITORY_LINKSTATUS_HPP_
#define CRAWLER_LINKENTRYREPOSITORY_LINKSTATUS_HPP_

enum class LinkStatus {
  WAITING,
  LOADED,
  INVALID
};

#endif //CRAWLER_LINKENTRYREPOSITORY_LINKSTATUS_HPP_
